package fsync

// Code generated by github.com/launchdarkly/go-options.  DO NOT EDIT.

type ApplyOptionFunc func(c *foptions) error

func (f ApplyOptionFunc) apply(c *foptions) error {
	return f(c)
}

func newFoptions(options ...Option) (foptions, error) {
	var c foptions
	err := applyFoptionsOptions(&c, options...)
	return c, err
}

func applyFoptionsOptions(c *foptions, options ...Option) error {
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

type Option interface {
	apply(*foptions) error
}

func OptionBufferSize(o int) ApplyOptionFunc {
	return func(c *foptions) error {
		c.BufferSize = o
		return nil
	}
}
