name: golint
on:
  push:
  pull_request:
jobs:
  golint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: './pkg/...'
